# add_newline = false

[character]
symbol = "Ï€"
error_symbol = "[Ï€](bold red) "
success_symbol = "[Ï€](bold green) "
vicmd_symbol = "[Ï€](bold green)"

[line_break]
# disabled = true

[package]
disabled = true

[directory]
style = "bold cyan"
truncate_to_repo = false
truncation_length = 5

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"
